In [1]:
import numpy as np

In [7]:
def sigmoid(t):
    return 1 / (1 + np.exp(-t))

In [8]:
x = np.random.normal(size=(2, 3))
print(x)

[[-0.85353788 -1.2203843   0.24238723]
 [ 0.60451557  0.02135884 -1.14206377]]


In [9]:
np.apply_along_axis(sigmoid, axis=1, arr=x)

array([[0.29869123, 0.22786883, 0.56030186],
       [0.64668872, 0.50533951, 0.24194165]])